name: pilisp
description: An interpreted Lisp inspired by Clojure. Runs on all Dart targets.
version: 1.0.0-alpha.6
repository: https://github.com/pilisp/pilisp

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  build_runner: ^2.3.2
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  build: ^2.3.1
  fast_immutable_collections: ^7.4.1
  source_gen: ^1.2.4
